- name: Manage nginx on ubuntu
  hosts: all
  become: true
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present
      update_cache: yes

  - name: Remove nginx
    apt:
      name: nginx
      state: absent
      purge: yes

  - name: Create www-data user
    user:
      name: www-data
      group: www-data
      home: /var/www
      state: present
      create_home: yes


